/**
 * @roundtable/domain — pure types and deterministic functions.
 *
 * No IO. No fetch, database, filesystem, Date.now() or Math.random(). This is
 * enforced by lint rules in eslint.config.js; see AGENTS.md R1 and doc 09 §9.2
 * for why the purity matters (web and api both run this code and must agree).
 */
export * from './result.js'
export * from './assert-never.js'
export * from './ids.js'
export * from './card.js'
export * from './role.js'
export * from './combo.js'
export * from './combo-index.js'
export * from './combo-patch.js'
export * from './role-derivation.js'
export * from './archetype-targets.js'
export * from './bracket-rules.js'
export * from './bracket-barometers.js'
export * from './legality.js'
export * from './composition-analysis.js'
export * from './color-balance.js'
export * from './scoring.js'
export * from './recommend.js'
export * from './query/index.js'
export * from './decklist/index.js'
export * from './deck.js'
export * from './deck-command.js'
export * from './bracket.js'
export * from './archetype.js'
export * from './composition.js'
export * from './target-overrides.js'
export * from './semantic-emphasis.js'
export * from './columns.js'
export * from './impact.js'
export * from './impact-roles.js'
export * from './efficiency.js'
export * from './curve.js'
export * from './synergy.js'
export * from './qualifiers.js'
export * from './answer-scope.js'
export * from './semantic-tokens.js'
export * from './cut.js'
export * from './oracle-refs.js'
export * from './recommendation.js'
export * from './quickbuild.js'
export * from './staples.js'
